### PR TITLE
Problem: (fix #4)Missing documentation for state sync

### LINKED ISSUE #4: Problem: Missing documentation for state sync
> State sync rapidly bootstraps a new node by discovering, fetching, and restoring a state machine snapshot from peers instead of fetching and replaying historical blocks

state sync option has to be enabled in `config.toml`. We can experiment and document the feature and see what's the speed improvement of it.

### PR DESCRIPTION
**Pull request by allthatjazzleo**
Solution: add guide for state-sync configuration

### CODE REVIEW

**Comment by lezzokafka** [comment]
Should we also change the the log for statesync to `debug`? 
 i.e.`log_level = "main:info,state:info,statesync:debug,*:error"`
So the the user will be able to view the snapshots requests and so on.

**Comment by allthatjazzleo** [comment]
> Should we also change the the log level for statesync to `debug`?
> i.e.`log_level = "main:info,state:info,statesync:debug,*:error"`
> So the the user will be able to view the snapshots requests and so on.
> Screen Shot 2020-11-12 at 3 53 54 pm

I think it is optional.
I added the advice for log-level for the guide.

**Review by tomtau — APPROVED** [review]

**Pull request merged**
